### PR TITLE
CLDR-15715 basic ci

### PR DESCRIPTION
**Pull request by srl295**
- .gitignore target
- add dependabot info
- basic maven target to verify buildability

### CODE REVIEW

**Comment by srl295** [comment]
@btangmu  just to give a basic sanity compilation…

**Comment by srl295** [comment]
'build' is set to only run if the pom.xml or source code changes.

**Review by btangmu — APPROVED** [review]
awesome!

**Comment by btangmu** [comment]
How does this relate to CLDR-15707?

**Comment by srl295** [comment]
> How does this relate to CLDR-15707?

I thought that was the ticket this was being done under.  is there a better one.?

**Comment by btangmu** [comment]
> 



> > How does this relate to CLDR-15707?
> 
> I thought that was the ticket this was being done under. is there a better one.?

https://unicode-org.atlassian.net/browse/CLDR-15715 is what most recently drove me to work on webdriver -- with the hope of stress-testing to reproduce something similar to recent "thousands of threads" bugs in production

**Comment by srl295** [comment]
just a typo then

**Pull request merged**
